Create user
code4romania/sunrise pull request #25
Opened 2024-05-20 21:52 UTC by alexPopaCode4

2024-05-21 11:35 UTC, andreiio commented on app/Filament/Organizations/Resources/UserResource.php
> +                    ->label(__('user.labels.last_login_at')),
subquery

2024-05-21 11:35 UTC, andreiio commented on app/Filament/Organizations/Resources/UserResource.php
> +                ])
enum validation

2024-05-21 11:35 UTC, andreiio commented on app/Filament/Organizations/Resources/UserResource/Pages/ViewUser.php
> +        );
```suggestion
        return $form->schema([
                Group::make([
                    Placeholder::make('status')
                        ->content(fn (User $record) => $record->status?->label()),
                    Placeholder::make('updated_at')
                        ->content(fn (User $record) => $record->updated_at),
                ])
                    ->columns()
                    ->columnSpanFull()],
                ...UserResource::getSchema()
        );
```

2024-05-21 11:35 UTC, andreiio commented on app/Models/User.php
> +        'roles' => 'json',
cast `AsEnumCollection::class`

2024-05-21 11:35 UTC, andreiio commented on app/Models/User.php
> +    }
make them filament actions

2024-06-14 12:18 UTC, andreiio requested changes

2024-06-14 12:18 UTC, andreiio commented on app/Models/User.php
> +            ->pluck('full_name', 'id');
```suggestion
        return Filament::getTenant()
            ->users
            ->pluck('full_name', 'id')
```

2024-06-17 09:55 UTC, andreiio requested changes

2024-06-17 09:55 UTC, andreiio commented on app/Filament/Organizations/Resources/UserResource/Pages/ViewUser.php
> +                ->columnSpanFull()],
```suggestion
            Group::make([
                Placeholder::make('status')
                    ->content(fn (User $record) => $record->status?->label()),
                Placeholder::make('updated_at')
                    ->content(fn (User $record) => $record->updated_at),
            ])
                ->columns()
                ->columnSpanFull(),
```

2024-06-17 09:55 UTC, andreiio commented on app/Filament/Organizations/Resources/UserResource/Pages/ViewUser.php
> +    public function form(Form $form): Form
De schimbat în `Infolist` sau de mutat cu totul în `EditUser`

2024-06-17 09:55 UTC, andreiio commented on app/Filament/Organizations/Resources/UserResource/Pages/ViewUser.php
> +                ->action(fn (User $record) => $record->resetPassword()),
Mută-l într-o acțiune separată

2024-06-17 09:55 UTC, andreiio commented on app/Filament/Organizations/Resources/UserResource/Pages/ViewUser.php
> +                ->visible(fn (User $record) => UserStatus::isValue($record->status, UserStatus::ACTIVE))
```php
UserStatus::isValue($record->status, UserStatus::ACTIVE)
```

ar trebui definit în `User` model sau într-un `HasUserStatus` trait:

```php
public function isActive(): bool
{
    return UserStatus::isValue($this->status, UserStatus::ACTIVE);
}
```

și folosit unde ai nevoie de el așa:

```php
->visible(fn (User $record) => $record->isActive())
```

2024-07-01 06:42 UTC, gheorghelupu17 approved these changes

2024-07-01 06:42 UTC, merged