332 update the informatii caz section
code4romania/sunrise pull request #353
Opened 2024-11-26 19:42 UTC by alexPopaCode4

2024-11-27 21:58 UTC, gheorghelupu17 requested changes

2024-11-27 21:58 UTC, gheorghelupu17 commented on app/Filament/Organizations/Resources/BeneficiaryResource/Pages/EditBeneficiaryPersonalInformation.php
> +
Ce se intampla, state nu e num ? esti pe create si e int nu Enum ?

2024-11-27 21:58 UTC, gheorghelupu17 commented on app/Filament/Organizations/Resources/BeneficiaryResource/Pages/EditBeneficiaryPersonalInformation.php
> +
La fel ca mai sus

2024-11-28 16:02 UTC, alexPopaCode4 commented on app/Filament/Organizations/Resources/BeneficiaryResource/Pages/EditBeneficiaryPersonalInformation.php
> +
functioneaza fara probleme

2024-11-29 11:17 UTC, merged